const {PGlite}=await import(process.env.PGLITE_MODULE || '@electric-sql/pglite');
import fs from 'node:fs';
import path from 'node:path';
import assert from 'node:assert/strict';
const root=process.argv[2] || process.cwd();
const db=new PGlite();
await db.exec(`create role anon; create role authenticated; create role service_role bypassrls;
create schema auth; create schema storage;
create table auth.users(id uuid primary key);
create function auth.uid() returns uuid language sql stable as $$select nullif(current_setting('request.jwt.claim.sub',true),'')::uuid$$;
create table storage.buckets(id text primary key,name text,public boolean,file_size_limit bigint,allowed_mime_types text[]);
create table storage.objects(id uuid primary key default gen_random_uuid(),bucket_id text,name text,owner_id text);
alter table storage.objects enable row level security;
grant usage on schema public,auth,storage to authenticated,anon,service_role;
grant select,insert,update,delete on storage.objects to authenticated;
alter default privileges in schema public grant select,insert,update,delete on tables to authenticated,service_role;
create publication supabase_realtime;`);
for(const f of fs.readdirSync(path.join(root,'supabase/migrations')).sort()){
 const sql=fs.readFileSync(path.join(root,'supabase/migrations',f),'utf8').replace('create extension if not exists pgcrypto;','');
 await db.exec(sql);console.log('Migration OK:',f);
}
const id=(n)=>`00000000-0000-0000-0000-${String(n).padStart(12,'0')}`;
await db.exec(`insert into departments(id,name,code) values('${id(1)}','Department A','A'),('${id(2)}','Department B','B');
insert into auth.users(id) values ${[10,11,12,13,14,15].map(n=>`('${id(n)}')`).join(',')};
insert into profiles(id,name,email,role,department_id) values
('${id(10)}','Super','super@test.edu','super_admin',null),('${id(11)}','HOD A','hod@test.edu','hod','${id(1)}'),('${id(12)}','Advisor A','a@test.edu','advisor','${id(1)}'),('${id(13)}','Advisor B','b@test.edu','advisor','${id(2)}'),('${id(14)}','Student A','s@test.edu','student','${id(1)}'),('${id(15)}','HOD B','hodb@test.edu','hod','${id(2)}');
insert into classes(id,department_id,year,section,batch,advisor_id,promotion_due) values('${id(20)}','${id(1)}',1,'A',2026,'${id(12)}',current_date),('${id(21)}','${id(2)}',4,'B',2023,'${id(13)}',current_date);
insert into students(id,class_id,user_id,name,register_number) values('${id(30)}','${id(20)}','${id(14)}','Student A','REG001'),('${id(31)}','${id(21)}',null,'Student B','REG002');`);
let passes=0;
async function as(n){await db.exec(`reset role;set role authenticated;select set_config('request.jwt.claim.sub','${id(n)}',false);`);}
async function ok(name,fn){await fn();passes++;console.log('PASS',name);}
async function denied(sql){await assert.rejects(()=>db.exec(sql));}
const count=async(sql)=>(await db.query(sql)).rows.length;
await as(12);
await ok('Advisor sees only allocated class and students',async()=>{assert.equal(await count('select * from students'),1);assert.equal(await count('select * from classes'),1);});
await ok('Advisor cannot access other department',async()=>assert.equal(await count(`select * from students where id='${id(31)}'`),0));
await ok('Advisor cannot self-promote',()=>denied(`update profiles set role='super_admin' where id='${id(12)}'`));
await ok('Advisor cannot backdate attendance',()=>denied(`insert into attendance(student_id,day,status) values('${id(30)}',current_date-1,'present')`));
await ok('Advisor cannot mark future attendance',()=>denied(`insert into attendance(student_id,day,status) values('${id(30)}',current_date+1,'present')`));
await ok('Advisor cannot mark other class',()=>denied(`insert into attendance(student_id,day,status) values('${id(31)}',(now() at time zone 'Asia/Kolkata')::date,'present')`));
await ok('Advisor marks current day',()=>db.exec(`select mark_attendance((now() at time zone 'Asia/Kolkata')::date,'[{"student_id":"${id(30)}","status":"uninformed"}]')`));
await ok('Advisor cannot overwrite saved attendance',()=>denied(`select mark_attendance((now() at time zone 'Asia/Kolkata')::date,'[{"student_id":"${id(30)}","status":"present"}]')`));
await ok('Informed leave requires letter',()=>denied(`insert into leaves(student_id,start_date,end_date,kind,reason) values('${id(30)}',current_date,current_date,'informed','Test')`));
await ok('Uninformed leave requires parent call',()=>denied(`insert into leaves(student_id,start_date,end_date,kind,reason) values('${id(30)}',current_date,current_date,'uninformed','Fake reason')`));
await db.exec(`insert into storage.objects(bucket_id,name,owner_id) values('call-recordings','${id(30)}/call.mp3','${id(12)}')`);
const call=(await db.query(`select save_call('${id(30)}','${id(30)}/call.mp3','Parent confirmed illness',true) id`)).rows[0].id;
await ok('Advisor cannot read recordings metadata or files',async()=>{assert.equal(await count('select * from call_records'),0);assert.equal(await count("select * from storage.objects where bucket_id='call-recordings'"),0);});
await db.exec(`insert into leaves(id,student_id,start_date,end_date,kind,reason,call_id) values('${id(40)}','${id(30)}',current_date,current_date,'uninformed','Client reason','${call}')`);
await ok('Parent response automatically becomes slip reason',async()=>assert.equal((await db.query('select reason from leaves')).rows[0].reason,'Parent confirmed illness'));
await ok('Advisor cannot approve own slip',()=>denied(`update leaves set status='approved' where id='${id(40)}'`));
await as(14);
await ok('Student only sees own record and cannot mark attendance',async()=>{assert.equal(await count('select * from students'),1);await denied(`insert into attendance(student_id,day,status) values('${id(30)}',current_date-2,'present')`);assert.equal(await count('select * from call_records'),0);});
await as(11);
await ok('Low attendance alerts reach HOD',async()=>assert.equal(await count("select * from notifications where message like '%below 75%'"),1));
await ok('HOD can read own department recordings',async()=>assert.equal(await count('select * from call_records'),1));
await ok('HOD approves slip and corrects historical attendance',async()=>{await db.exec(`update leaves set status='approved',decision_note='Reviewed history' where id='${id(40)}';select mark_attendance((now() at time zone 'Asia/Kolkata')::date-2,'[{"student_id":"${id(30)}","status":"present"}]');`);});
await as(12);
await ok('Advisor receives HOD decision',async()=>assert.equal(await count("select * from notifications where message like 'Pink slip approved%'"),1));
const promo=(await db.query(`select request_promotion('${id(20)}') id`)).rows[0].id;
await ok('Advisor cannot approve promotion',()=>denied(`select review_promotion('${promo}',true)`));
await as(11);
await ok('HOD cannot bypass annual approval through class CRUD',()=>denied(`update classes set year=4 where id='${id(20)}'`));
await ok('HOD cannot directly archive students',()=>denied(`update students set active=false where id='${id(30)}'`));
await ok('Approved promotion increments year exactly once',async()=>{await db.exec(`select review_promotion('${promo}',true)`);assert.equal((await db.query(`select year from classes where id='${id(20)}'`)).rows[0].year,2);await denied(`select review_promotion('${promo}',true)`);});
await as(15);
await ok('Other HOD cannot view recordings',async()=>assert.equal(await count('select * from call_records'),0));
const completion=(await db.query(`select request_promotion('${id(21)}') id`)).rows[0].id;
await db.exec(`select review_promotion('${completion}',true)`);
await ok('Completion preserves history for HOD',async()=>{const row=(await db.query(`select * from students where id='${id(31)}'`)).rows[0];assert.equal(row.active,false);assert.ok(row.completed_at);});
await as(13);
await ok('Completed students hidden from advisor',async()=>assert.equal(await count('select * from students'),0));
await as(10);
await ok('Super Admin can inspect audit trail',async()=>assert.ok(await count('select * from audit_logs')>0));
await as(14);
await ok('Student cannot reuse staff call evidence to create uninformed leave',()=>denied(`insert into leaves(student_id,start_date,end_date,kind,reason,call_id) values('${id(30)}',current_date+1,current_date+1,'uninformed','Forged','${call}')`));
await db.exec('reset role');
await ok('Database prevents disabling an assigned account',()=>denied(`update profiles set active=false where id='${id(14)}'`));
await db.exec(`update students set user_id=null where id='${id(30)}';update profiles set active=false where id='${id(14)}'`);
await as(14);
await ok('Disabled student cannot read personal history',async()=>assert.equal(await count('select * from students'),0));
await as(12);
await ok('Advisor cannot run the privileged scheduler RPC',()=>denied('select queue_due_promotions()'));

await as(11);
await ok('Approved leave reconciles already marked attendance',async()=>assert.equal((await db.query(`select status from attendance where student_id='${id(30)}' and day=current_date`)).rows[0].status,'informed'));
await ok('Approved leave prevents a present override',async()=>{await db.exec(`select mark_attendance((now() at time zone 'Asia/Kolkata')::date,'[{"student_id":"${id(30)}","status":"present"}]')`);assert.equal((await db.query(`select status from attendance where student_id='${id(30)}' and day=(now() at time zone 'Asia/Kolkata')::date`)).rows[0].status,'informed');});
await ok('Managers cannot mark a future date',()=>denied(`select mark_attendance(current_date+2,'[{"student_id":"${id(30)}","status":"present"}]')`));
await ok('Managers cannot bypass complete-roster RPC',()=>denied(`insert into attendance(student_id,day,status) values('${id(30)}',current_date-10,'present')`));
await db.exec(`insert into students(id,class_id,name,register_number,degree) values('${id(32)}','${id(20)}','Second student','REG003','Degree');`);
await ok('Incomplete roster is rejected',()=>denied(`select mark_attendance(current_date-3,'[{"student_id":"${id(30)}","status":"present"}]')`));
await ok('Duplicate roster is rejected',()=>denied(`select mark_attendance(current_date-3,'[{"student_id":"${id(30)}","status":"present"},{"student_id":"${id(30)}","status":"present"}]')`));
await ok('Invalid status rolls back the complete submission',async()=>{await denied(`select mark_attendance(current_date-3,'[{"student_id":"${id(30)}","status":"present"},{"student_id":"${id(32)}","status":"invalid"}]')`);assert.equal(await count('select * from attendance where day=current_date-3'),0);});
await ok('Full valid roster is stored atomically',async()=>{await db.exec(`select mark_attendance(current_date-3,'[{"student_id":"${id(30)}","status":"present"},{"student_id":"${id(32)}","status":"uninformed"}]')`);assert.equal(await count('select * from attendance where day=current_date-3'),2);});
await ok('Reviewed leave cannot be rewritten or deleted',async()=>{await denied(`update leaves set start_date=current_date-9 where id='${id(40)}'`);await denied(`delete from leaves where id='${id(40)}'`);});
await ok('Referenced recording cannot be deleted',async()=>{await db.exec(`delete from storage.objects where bucket_id='call-recordings'`);assert.equal(await count("select * from storage.objects where bucket_id='call-recordings'"),1);});
await ok('Class edits update allowed fields',()=>db.exec(`update classes set section='Custom Section',batch=2026,advisor_id='${id(12)}',promotion_due=current_date+365 where id='${id(20)}'`));
await db.exec(`insert into timetable_entries(class_id,weekday,period,subject,starts_at,ends_at) values('${id(20)}',1,1,'Configured subject','09:00','10:00');insert into notices(department_id,title,body) values('${id(1)}','College notice','Entered by the HOD');`);
await as(15);
await ok('Timetable and notices stay in their department',async()=>{assert.equal(await count('select * from timetable_entries'),0);assert.equal(await count('select * from notices'),0);});
await as(12);
await ok('Advisor can read but cannot edit timetable',async()=>{assert.equal(await count('select * from timetable_entries'),1);await denied(`insert into timetable_entries(class_id,weekday,period,subject,starts_at,ends_at) values('${id(20)}',2,1,'Unauthorized','09:00','10:00')`);});
await as(10);
await ok('Custom course duration governs completion',async()=>{
 await db.exec(`insert into classes(id,department_id,year,course_years,section,batch,promotion_due) values('${id(22)}','${id(1)}',2,2,'Masters',2025,current_date);`);
 const p=(await db.query(`select request_promotion('${id(22)}') id`)).rows[0].id;
 await db.exec(`select review_promotion('${p}',true)`);
 assert.equal((await db.query(`select active from classes where id='${id(22)}'`)).rows[0].active,false);
});
console.log(`${passes} authorization and workflow tests passed.`);
await db.close();
