import type { Row, Data } from './api';

export const primaryHODProfile: Row = {
  id: 'u-hod-aids',
  name: 'Dr. K. Manivannan',
  email: 'hod.manivannan@vsb.edu.in',
  role: 'hod',
  department_id: 'dept-aids',
  active: true,
  password: 'Hod@12345678',
};

export const primaryAdminProfile: Row = {
  id: 'u-super-admin',
  name: 'Principal / Super Admin',
  email: 'admin@vsb.edu.in',
  role: 'super_admin',
  department_id: null,
  active: true,
  password: 'Admin@12345678',
};

export const initialMockData: Data = {
  departments: [
    {
      id: 'dept-aids',
      name: 'Artificial Intelligence & Data Science',
      code: 'AI & DS',
    },
    {
      id: 'dept-cse',
      name: 'Computer Science & Engineering',
      code: 'CSE',
    },
    {
      id: 'dept-ece',
      name: 'Electronics & Communication Engineering',
      code: 'ECE',
    },
  ],
  profiles: [
    primaryHODProfile,
    primaryAdminProfile,
  ],
  classes: [
    // Year 1 (2026 Batch) - 4 Sections: A, B, C, D
    {
      id: 'class-1a',
      department_id: 'dept-aids',
      year: 1,
      course_years: 4,
      section: 'A',
      batch: 2026,
      promotion_due: '2027-06-30',
      advisor_id: null,
      active: true,
    },
    {
      id: 'class-1b',
      department_id: 'dept-aids',
      year: 1,
      course_years: 4,
      section: 'B',
      batch: 2026,
      promotion_due: '2027-06-30',
      advisor_id: null,
      active: true,
    },
    {
      id: 'class-1c',
      department_id: 'dept-aids',
      year: 1,
      course_years: 4,
      section: 'C',
      batch: 2026,
      promotion_due: '2027-06-30',
      advisor_id: null,
      active: true,
    },
    {
      id: 'class-1d',
      department_id: 'dept-aids',
      year: 1,
      course_years: 4,
      section: 'D',
      batch: 2026,
      promotion_due: '2027-06-30',
      advisor_id: null,
      active: true,
    },

    // Year 2 (2025 Batch) - 4 Sections: A, B, C, D
    {
      id: 'class-2a',
      department_id: 'dept-aids',
      year: 2,
      course_years: 4,
      section: 'A',
      batch: 2025,
      promotion_due: '2027-06-30',
      advisor_id: null,
      active: true,
    },
    {
      id: 'class-2b',
      department_id: 'dept-aids',
      year: 2,
      course_years: 4,
      section: 'B',
      batch: 2025,
      promotion_due: '2027-06-30',
      advisor_id: null,
      active: true,
    },
    {
      id: 'class-2c',
      department_id: 'dept-aids',
      year: 2,
      course_years: 4,
      section: 'C',
      batch: 2025,
      promotion_due: '2027-06-30',
      advisor_id: null,
      active: true,
    },
    {
      id: 'class-2d',
      department_id: 'dept-aids',
      year: 2,
      course_years: 4,
      section: 'D',
      batch: 2025,
      promotion_due: '2027-06-30',
      advisor_id: null,
      active: true,
    },

    // Year 3 (2024 Batch) - 4 Sections: A, B, C, D
    {
      id: 'class-3a',
      department_id: 'dept-aids',
      year: 3,
      course_years: 4,
      section: 'A',
      batch: 2024,
      promotion_due: '2027-06-30',
      advisor_id: null,
      active: true,
    },
    {
      id: 'class-3b',
      department_id: 'dept-aids',
      year: 3,
      course_years: 4,
      section: 'B',
      batch: 2024,
      promotion_due: '2027-06-30',
      advisor_id: null,
      active: true,
    },
    {
      id: 'class-3c',
      department_id: 'dept-aids',
      year: 3,
      course_years: 4,
      section: 'C',
      batch: 2024,
      promotion_due: '2027-06-30',
      advisor_id: null,
      active: true,
    },
    {
      id: 'class-3d',
      department_id: 'dept-aids',
      year: 3,
      course_years: 4,
      section: 'D',
      batch: 2024,
      promotion_due: '2027-06-30',
      advisor_id: null,
      active: true,
    },

    // Year 4 (2023 Batch) - 2 Sections: A, B
    {
      id: 'class-4a',
      department_id: 'dept-aids',
      year: 4,
      course_years: 4,
      section: 'A',
      batch: 2023,
      promotion_due: '2027-06-30',
      advisor_id: null,
      active: true,
    },
    {
      id: 'class-4b',
      department_id: 'dept-aids',
      year: 4,
      course_years: 4,
      section: 'B',
      batch: 2023,
      promotion_due: '2027-06-30',
      advisor_id: null,
      active: true,
    },
  ],
  students: [],
  attendance: [],
  leaves: [],
  calendar_events: [],
  timetable_entries: [],
  notices: [],
  notifications: [],
  promotions: [],
  call_records: [],
  audit_logs: [],
};
